name: Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches-ignore:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn

      - name: Install Dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile

      - name: Lint
        uses: super-linter/super-linter/slim@v5
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TYPESCRIPT_DEFAULT_STYLE: prettier
          VALIDATE_JSCPD: false
