name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-jest:
    name: Jest Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn

      - name: Install Dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile

      - name: Check Format
        uses: borales/actions-yarn@v4
        with:
          cmd: format:check

      - name: Lint
        uses: borales/actions-yarn@v4
        with:
          cmd: lint

      - name: Run Tests
        uses: borales/actions-yarn@v4
        with:
          cmd: ci-test

  test-action:
    name: Action Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Action
        uses: ./
        with:
          name: "TestEvent"
          user: "TestUser"
          properties: "{}"

      - name: Print Output
        run: echo "success:"${{ steps.test-action.outputs }}"
