name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-jest:
    name: Rudderstack Jest Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Check Format
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Run Tests
        run: npm run ci-test

  test-action:
    name: Rudderstack Action Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Action
        uses: ./
        with:
          name: "TestEvent"
          user: "TestUser"
          properties: ""

      - name: Print Output
        id: output
        run: echo "success:"${{ steps.test-action.outputs.success }}"
