name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-jest:
    name: Jest Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn

      - name: Install Dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile

      - name: Check Format
        uses: borales/actions-yarn@v4
        with:
          cmd: format:check

      - name: Lint
        uses: borales/actions-yarn@v4
        with:
          cmd: lint

      - name: Run Tests
        uses: borales/actions-yarn@v4
        with:
          cmd: test

  test-action:
    name: Action Test
    runs-on: ubuntu-latest
    env:
      RUDDERSTACK_DATAPLANE_URL:  ${{ secrets.RUDDERSTACK_DATAPLANE_URL }}
      RUDDERSTACK_WRITE_KEY:  ${{ secrets.RUDDERSTACK_WRITE_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn

      - name: Install Dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile
  
      - name: Build Action
        uses: borales/actions-yarn@v4
        with:
          cmd: bundle

      - name: Run Action
        id: run
        uses: ./
        with:
          name: "TestEvent"
          user: "TestUser"
          properties: "{}"

      - name: Print Output
        run: "echo \"success: ${{ steps.run.outputs.success }}\""
